- name: Fix security group
  hosts: localhost
  gather_facts: no
  connection: local
  
  tasks:

    - name: Get facts for one security group
      azure_rm_securitygroup_info:
        resource_group: "{{ env }}-resource"
        name: "{{ vm_name }}"
      register: sg

    - azure_rm_securitygroup:
        resource_group: "{{ env }}-resource"
        name: "{{ vm_name }}"
        rules:
          - name: "{{ item.name }}"
            priority: "{{ item.properties.priority }}"
            access: Deny
            destination_port_range: "{{ item.properties.destinationPortRange }}"
            protocol: "{{ item.properties.protocol }}"
            direction: "{{ item.properties.direction }}"
      when:
        - item.properties.destinationPortRange == port
        - item.properties.direction|lower == direction|lower
      loop: "{{ sg.securitygroups[0].properties.securityRules }}"

