- name: Fix security group
  hosts: localhost
  gather_facts: no
  connection: local
  
  tasks:

    - azure_rm_securitygroup:
        resource_group: "{{ env }}-resource"
        name: "{{ vm_name }}"
        purge_rules: yes
        rules:
          - name: Allow HTTP
            priority: 101
            access: Allow
            destination_port_range: 80
            protocol: Tcp
            direction: Inbound
          - name: Allow HTTPS
            priority: 102
            access: Allow
            destination_port_range: 443
            protocol: Tcp
            direction: Inbound
          - name: Allow WinRM
            priority: 103
            access: Allow
            destination_port_range: 5985
            protocol: Tcp
            direction: Inbound
          - name: Allow WinRMS
            priority: 104
            access: Allow
            destination_port_range: 5986
            protocol: Tcp
            direction: Inbound
          - name: Deny RDP
            priority: 105
            access: Deny
            destination_port_range: 3389
            protocol: Tcp
            direction: Inbound
