---
- name: Harden Server
  hosts: "{{ vm_name }}"
  become: "{% if vm == 'Windows' %}false{% else %}true{% endif %}"
  vars_files:
    - 'vars/harden.yml'
  tasks:
    - include_role:
        name: "{{ harden_role[vm] }}"
