- name: Fix security group
  hosts: localhost
  gather_facts: no
  connection: local
  
  tasks:

    - azure_rm_securitygroup:
        resource_group: "{{ env }}-resource"
        name: "{{ sg_name }}"
        purge_rules: yes
        rules:
          - name: Proxy
            priority: 101
            access: Allow
            destination_port_range: 8080
            protocol: Tcp
            direction: Inbound
          - name: HTTPS
            priority: 102
            access: Allow
            destination_port_range: 443
            protocol: Tcp
            direction: Inbound
          - name: WinRM
            priority: 103
            access: Allow
            destination_port_range: 5985
            protocol: Tcp
            direction: Inbound
          - name: WinRMS
            priority: 104
            access: Allow
            destination_port_range: 5986
            protocol: Tcp
            direction: Inbound
          - name: RDP
            priority: 105
            access: Allow
            destination_port_range: 3389
            protocol: Tcp
            direction: Inbound
