harden_rhel7_pam_services:    # AD.1.1.1.0.0
  - name: login
    type: auth
    control: include
    mpath: postlogin
    ntype: auth
    ncontrol: include
    nmpath: system-auth
    state: after 
  - name: login
    type: account
    control: required
    mpath: pam_nologin.so
    ntype: account
    ncontrol: include
    nmpath: system-auth
    state: after
  - name: login
    type: account 
    control: include
    mpath: system-auth
    ntype: password
    ncontrol: include
    nmpath: system-auth
    state: after

  - name: passwd
    type: account
    control: include
    mpath: system-auth
    ntype: auth
    ncontrol: include
    nmpath: system-auth
    state: before 
  - name: passwd
    type: auth
    control: include
    mpath: system-auth
    ntype: account
    ncontrol: include
    nmpath: system-auth
    state: after
  - name: passwd
    type: account 
    control: include
    mpath: system-auth
    ntype: password
    ncontrol: include
    nmpath: system-auth
    state: after

  - name: sshd
    type: auth
    control: include
    mpath: postlogin
    ntype: auth
    ncontrol: include
    nmpath: system-auth
    state: after 
  - name: sshd
    type: account
    control: include
    mpath: password-auth
    ntype: account
    ncontrol: include
    nmpath: system-auth
    state: after
  - name: sshd
    type: account 
    control: include
    mpath: password-auth
    ntype: password
    ncontrol: include
    nmpath: system-auth
    state: after

  - name: su
    type: auth
    control: sufficient
    mpath: pam_rootok.so
    ntype: auth
    ncontrol: include
    nmpath: system-auth
    state: after 
  - name: su
    type: account
    control: sufficient
    mpath: pam_succeed_if.so
    ntype: account
    ncontrol: include
    nmpath: system-auth
    state: after
  - name: su
    type: session 
    control: include
    mpath: system-auth
    ntype: password
    ncontrol: include
    nmpath: system-auth
    state: before

harden_rhel7_pam_system_password:  # AD.1.1.2 AD.1.1.4.1 AD.1.1.6.0 AD.1.4.1
  - name: system-auth
  - name: password-auth

harden_rhel7_pass_max_days: 90  # AD.1.1.1.1 and AD.1.1.1.2

harden_rhel7_pass_min_len: 8    # AD.1.1.2

harden_rhel7_pass_min_days: 1   # AD.1.1.3.1

harden_rhel7_exclude_users:     # AD.1.1.1.2
  - root

TCIM_user_AD_20_1_2_4: tcimuser   # AD.20.1.2.4

denyusers:                      # AD.1.1.13.2
  - root
  - bin
  - daemon
  - adm
  - lp
  - sync
  - shutdown
  - halt
  - mail
  - news
  - uucp
  - operator
  - games
  - nobody

ftpusers:                         # AD.1.1.13.3
  - root
  - bin
  - daemon
  - adm
  - lp
  - sync
  - shutdown
  - halt
  - mail
  - news
  - uucp
  - operator
  - games
  - nobody

mounts:
  tmp:
    size: 1024                # Size in Mb
    phy_device: /dev/sda2     # Physical Disk
    vg_name: cl               # Volume Group Name
    lv_name: lv_tmp           # Logical Volume Name
    fstype: ext4              # File System Type
  home:
    size: 5120                # Size in Mb
    phy_device: /dev/sda2     # Physical Disk
    vg_name: cl               # Volume Group Name
    lv_name: lv_home          # Logical Volume Name
    fstype: ext4              # File System Type
  var_log_audit:
    size: 1024                # Size in Mb
    phy_device: /dev/sda2     # Physical Disk
    vg_name: cl               # Volume Group Name
    lv_name: lv_var_log_audit # Logical Volume Name
    fstype: ext4              # File System Type
  var:
    size: 5120                # Size in Mb
    phy_device: /dev/sda2     # Physical Disk
    vg_name: cl               # Volume Group Name
    lv_name: lv_var           # Logical Volume Name
    fstype: ext4              # File System Type

# Enable or disable specific checks
ad_1_1_1_0_0: yes
ad_1_1_1_1: yes
ad_1_1_1_2: yes
ad_1_1_2: yes
ad_1_1_3_1: yes
ad_1_1_3_2: yes
ad_1_1_4_1: yes
ad_1_1_4_2: yes
ad_1_1_4_3: yes
ad_1_1_4_4: yes
ad_1_1_5: yes
ad_1_1_6_0: yes
ad_1_1_6_1: yes
ad_1_1_7_1: no
ad_1_1_7_2: no
ad_1_1_7_3: no
ad_1_1_8_1: yes
ad_1_1_8_2: yes
ad_1_1_8_3: yes
ad_1_1_9_0: yes
ad_1_1_9_1: yes
ad_1_1_10_0: yes
ad_1_1_10_1: no
ad_1_1_10_2: yes
ad_1_1_11_0: yes
ad_1_1_11_1: yes
ad_1_1_12_0: yes
ad_1_1_12_1: yes
ad_1_1_13_0: yes
ad_1_1_13_1_0: yes
ad_1_1_13_1_1: yes
ad_1_1_13_2: yes
ad_1_1_13_3: yes
ad_1_1_13_4: no
ad_1_2_1_1: yes
ad_1_2_1_2: yes
ad_1_2_1_3: yes
ad_1_2_1_4: yes
ad_1_2_1_5: yes
ad_1_2_2: yes
ad_1_2_3_1: yes
ad_1_2_3_2: yes
ad_1_2_4_1: yes
ad_1_2_4_2: yes
ad_1_2_5: yes
ad_1_2_6: yes
ad_1_3_0_: yes
ad_1_4_1: yes
ad_1_4_2: yes
ad_1_4_3: yes
ad_1_4_4: yes
ad_1_4_5: yes
ad_1_5_1_1: yes
ad_1_5_1_2: yes
ad_1_5_1_3: yes
ad_1_5_1_4: yes
ad_1_5_1_5: yes
ad_1_5_1_6: yes
ad_1_5_1_7: yes
ad_1_5_1_8: yes
ad_1_5_2_1: yes
ad_1_5_2_2: yes
ad_1_5_3_1: yes
ad_1_5_3_2: yes
ad_1_5_4_1: yes
ad_1_5_4_2: yes
ad_1_5_5: yes
ad_1_5_6: yes
ad_1_5_7: yes
ad_1_5_8_1: yes
ad_1_5_8_2: yes
ad_1_5_8_3: yes
ad_1_5_8_4: yes
ad_1_5_8_5: yes
ad_1_5_8_6: yes
ad_1_5_8_7: yes
ad_1_5_8_8: yes
ad_1_5_9_1: yes
ad_1_5_9_2: yes
ad_1_5_9_3: yes
ad_1_5_9_4: yes
ad_1_5_9_5: yes
ad_1_5_9_6: yes
ad_1_5_9_7: yes
ad_1_5_9_8: yes
ad_1_5_9_9: yes
ad_1_5_9_10: yes
ad_1_5_9_11: yes
ad_1_5_9_12: yes
ad_1_5_9_13: yes
ad_1_5_9_14: yes
ad_1_5_9_15: yes
ad_1_5_9_16: yes
ad_1_5_9_17: yes
ad_1_5_9_18: yes
ad_1_5_9_19: yes
ad_1_5_9_20: yes
ad_1_5_9_21: yes
ad_1_5_9_22: yes
ad_1_5_9_23: yes
ad_1_5_9_24: yes
ad_1_5_10_1: yes
ad_1_5_10_2: yes
ad_1_5_11: yes
ad_1_5_12_0: yes
ad_1_5_12_2: yes
ad_1_5_12_3: yes
ad_1_5_12_4: yes
ad_1_7_0: yes
ad_1_8_1: yes
ad_1_8_2_1: yes
ad_1_8_2_2: yes
ad_1_8_3_1: yes
ad_1_8_3_2: yes
ad_1_8_3_3: yes
ad_1_8_4_1: yes
ad_1_8_4_2: yes
ad_1_8_5_1: yes
ad_1_8_5_2: yes
ad_1_8_6_1: yes
ad_1_8_6_2: yes
ad_1_8_7_1: yes
ad_1_8_7_2: yes
ad_1_8_8: yes
ad_1_8_9: yes
ad_1_8_10: yes
ad_1_8_11: yes
ad_1_8_12_1_1: yes
ad_1_8_12_1_2: yes
ad_1_8_12_2: yes
ad_1_8_12_3: yes
ad_1_8_12_4: yes
ad_1_8_12_5: yes
ad_1_8_13_0: yes
ad_1_8_13_1: yes
ad_1_8_13_2: yes
ad_1_8_13_3: yes
ad_1_8_13_4: yes
ad_1_8_14_1: yes
ad_1_8_14_2: yes
ad_1_8_14_3: yes
ad_1_8_15_1: yes
ad_1_8_15_2: yes
ad_1_8_15_3: yes
ad_1_8_17_1: yes
ad_1_8_17_2: yes
ad_1_8_17_3: yes
ad_1_8_18_2: yes
ad_1_8_18_3: yes
ad_1_8_19_2: yes
ad_1_8_19_3: yes
ad_1_8_20_1: yes
ad_1_8_20_2: yes
ad_1_8_20_3: yes
ad_1_8_21_1: yes
ad_1_8_21_2: yes
ad_1_8_21_3: yes
ad_1_8_22_1: no
ad_1_8_22_2: no
ad_1_8_22_3: yes
ad_1_8_22_4: yes
ad_1_9_1_1: yes
ad_1_9_1_2: yes
ad_1_9_1_2_1: yes
ad_1_9_1_3: yes
ad_1_9_1_4: yes
ad_1_9_1_5: yes
ad_1_9_1_6: yes
ad_1_9_1_7: yes
ad_2_0_1: yes
ad_2_1_1: yes
ad_2_1_2: yes
ad_2_1_3_0: yes
ad_2_1_3_1: yes
ad_2_1_3_2: yes
ad_2_1_4: yes
ad_3_0_0: yes
ad_5_0_0: yes
ad_5_0_1: yes
ad_5_0_2: yes
ad_10_1_2_1: yes
ad_10_1_2_2: yes
ad_10_1_4_0: yes
ad_10_1_4_1: yes
ad_10_1_4_6: yes
ad_10_1_4_7: yes
ad_10_1_4_8: yes
ad_10_1_4_9: yes
ad_10_1_4_10: yes
ad_10_1_4_2: yes
ad_10_1_4_3: yes
ad_20_1_2_1: yes
ad_20_1_2_2: yes
ad_20_1_2_3_1: yes
ad_20_1_2_3_2: yes
ad_20_1_2_3_3: yes
ad_20_1_2_3_4: yes
ad_20_1_2_3_5: yes
ad_20_1_2_3_6: yes
ad_20_1_2_3_7: yes
ad_20_1_2_3_8: yes
ad_20_1_2_3_9: yes
ad_20_1_2_3_10: yes
ad_20_1_2_3_11: yes
ad_20_1_2_3_12: yes
ad_20_1_2_3_13: yes
ad_20_1_2_3_14: yes
ad_20_1_2_3_15: yes
ad_20_1_2_3_16: yes
ad_20_1_2_3_17: yes
ad_20_1_2_3_18: yes
ad_20_1_2_3_19: yes
ad_20_1_2_3_20: yes
ad_20_1_2_3_21: yes
ad_20_1_2_3_22: yes
ad_20_1_2_3_23: yes
ad_20_1_2_4: yes
ad_99_1_0: yes
ad_99_1_1: yes
ad_99_1_2: yes
ad_99_1_3: no
ad_99_1_4: no
ad_99_1_5: yes
ad_99_1_6: no
ad_99_1_7: yes
ad_99_1_8: yes
ad_99_1_9: yes
ad_99_1_10: yes
ad_99_1_11: yes
ad_99_1_12: yes
ad_99_1_13: yes
ad_99_1_14: yes
ad_99_1_15: yes
ad_99_1_16: yes
ad_99_1_17: yes
ad_99_1_18: yes
ad_99_1_19: yes
ad_99_1_20: yes
ad_99_1_21: yes
ad_99_1_22: yes
ad_99_1_23: yes
ad_99_1_25: no
ad_99_1_26: no
ad_99_1_27: yes
ad_99_1_28: no
ad_99_1_29: no
ad_99_1_30: no
ad_99_1_31: no
ad_99_1_32: no
ad_99_1_33: no
ad_99_1_34: no
ad_99_1_35: yes
ad_99_1_36: yes
ad_99_1_37: yes
ad_99_1_38: yes
ad_99_1_39: yes
ad_99_1_40: yes
ad_99_1_41: yes
ad_99_1_42: yes
ad_99_1_43: yes
ad_99_1_44: yes
ad_99_1_45: yes
ad_99_1_46: yes
ad_99_1_47: yes
ad_99_1_48: yes
ad_99_1_49: yes
ad_99_1_50: yes
ad_99_1_51: yes
ad_99_1_52: yes
ad_99_1_53: yes
ad_99_1_54: yes
ad_99_1_55: yes
ad_99_1_56: yes
ad_99_1_57: yes
ad_99_1_58: yes
ad_99_1_59: yes
ad_99_1_60: yes
ad_99_1_61: yes
ad_99_1_62: yes
