- name: Install Applications
  debug: 
    msg: "{{ apps[vm][item] }}.yml"
  loop: install_apps
  ignore_errors: true


- name: Install Applications
  include_tasks: "{{ apps[vm][item] }}.yml"
  loop: install_apps
  ignore_errors: true
