- name: Install YUM Packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ common[vm].packages }}"
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install Windows Chocolatey Packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ common[vm].packages }}"
  when: ansible_os_family == 'Windows'