---
- name: Set resource facts
  set_fact:
    azure_resource_group:  "{{ env }}-resource"
    azure_storage_account: "{{ (env + 'storage') | lower | regex_replace('[^0-9a-z]+', '') }}"
    azure_virtual_network: "{{ env }}-network"
    azure_virtual_subnet:  "{{ (env + 'subnet')  | lower | regex_replace('[^0-9a-z]+', '') }}"

################### Destroy Instances ###################
- name: Azure | Destroy instance
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ vm_name }}"
    started: False
    state: absent

################### Remove Network Interfaces ###################

- name: Azure | Delete network interface
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ vm_name + '01' }}"
    state: absent
  ignore_errors: yes

################### Remove Security Groups ###################

- name: Azure | Delete Security Group
  azure_rm_securitygroup:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ vm_name + '01' }}"
    state: absent
  ignore_errors: yes

################### Remove Public IP Addresses ###################

- name: Azure | Delete Public IP Addresses
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ vm_name + '01' }}"
    state: absent
  ignore_errors: yes

################### Remove from Tower ###################
- name: Get host
  uri:
    url: "{{ lookup('env', 'TOWER_HOST') }}/api/v2/hosts/?name={{ vm_name }}"
    method: GET
    user: "{{ lookup('env', 'TOWER_USERNAME') }}"
    password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 201
      - 400
  register: response
  changed_when: response.status == 201

- debug:
    var: response

################### Remove Subnets ###################

#- name: Azure | Destroy subnet
#  azure_rm_subnet:
#    resource_group: "{{ azure_resource_group }}"    
#    name: "{{ azure_virtual_subnet }}"
#    virtual_network_name: "{{ azure_virtual_network }}"
#    address_prefix_cidr: "{{ ptr_zone_cidr }}"     
#    state: absent
#  ignore_errors: yes

#- name: Azure | Destroy virtual network
#  azure_rm_virtualnetwork:
#    resource_group: "{{ azure_resource_group }}"  
#    name: "{{ azure_virtual_network }}" 
#    address_prefixes_cidr:
#        - "{{ ptr_zone_cidr }}"
#    state: absent
#  ignore_errors: yes

#- name: Azure | Destroy resource group
#  azure_rm_resourcegroup:
#    name: "{{ azure_resource_group }}"
#    location: "{{ azure_location }}"
#    state: absent
#  ignore_errors: yes

