#
# --------------------------------- AD.1.4.1 ---------------------------------
#
- name: AD.1.4.1 | PATCH_RHEL | SYSTEM SETTINGS | Enforce a default no access policy (PAM)
  pamd:
    name: "{{ item.name }}"
    type: account
    control: required
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_deny.so
    state: before
  with_items: "{{ harden_rhel7_pam_system_password }}"
  when: ad_1_4_1
  register: __ad_1_4_1
  tags:
    - AD.1.4.1
    - patch
    - system_settings
    - S

- name: AD.1.4.1 | AUDIT_RHEL | SYSTEM SETTINGS | Enforce a default no access policy (PAM)
  debug:
    msg: "{ __ad_1_4_1.results }"
  when:
    - ad_1_4_1
    - ansible_check_mode
    - __ad_1_4_1 | changed
  tags:
    - AD.1.4.1
    - audit
    - system_settings
    - S

#
# --------------------------------- AD.1.4.2 ---------------------------------
#
- name: AD.1.4.2 | GATHER_INFO_RHEL | SYSTEM SETTINGS | Restrict root ftp access
  stat:
    path: /etc/ftpusers
  when: ad_1_4_2
  register: __ad_1_4_2_ftpstat
  tags:
    - AD.1.4.2
    - audit
    - system_settings
    - S

- name: AD.1.4.2 | PATCH_RHEL | SYSTEM SETTINGS | Restrict root ftp access
  lineinfile:
    path: /etc/ftpusers
    line: "{{ item }}"
  with_items: 
    - root
  when:
    - ad_1_4_2
    - __ad_1_4_2_ftpstat.stat.exists
  register: __ad_1_4_2
  tags:
    - AD.1.4.2
    - patch
    - system_settings
    - S

- name: AD.1.4.2 | AUDIT_RHEL | SYSTEM SETTINGS | Restrict root ftp access
  debug:
    msg: "{{ __ad_1_4_2 }}"
  when: 
    - ad_1_4_2
    - ansible_check_mode
    - __ad_1_4_2_ftpstat.stat.exists
    - __ad_1_4_2 | changed
  tags:
    - AD.1.4.2
    - audit
    - system_settings
    - S

- name: AD.1.4.2 | GATHER_INFO_RHEL | SYSTEM SETTINGS | Restrict vsftpd access
  stat:
    path: /etc/vsftpd/ftpusers
  when: ad_1_4_2
  register: __ad_1_4_2_vsftpdstat
  tags:
    - AD.1.4.2
    - audit
    - system_settings
    - S

- name: AD.1.4.2 | PATCH_RHEL | SYSTEM SETTINGS | Restrict vsftpd access
  lineinfile:
    path: /etc/vsftpd/ftpusers
    line: "{{ item }}"
  with_items: 
    - root
  when:
    - ad_1_4_2
    - __ad_1_4_2_vsftpdstat.stat.exists
  register: __ad_1_4_2_vs
  tags:
    - AD.1.4.2
    - patch
    - system_settings
    - S

- name: AD.1.4.2 | AUDIT_RHEL | SYSTEM SETTINGS | Restrict vsftpd access
  debug:
    msg: "{{ __ad_1_4_2_vs.results }}"
  when: 
    - ad_1_4_2
    - ansible_check_mode
    - __ad_1_4_2_vsftpdstat.stat.exists
    - __ad_1_4_2_vs | changed
  tags:
    - AD.1.4.2
    - audit
    - system_settings
    - S
